const $=s=>document.querySelector(s);
const e={video:$("#video"),canvas:$("#overlay"),empty:$("#empty"),cameraBtn:$("#cameraBtn"),connectBtn:$("#connectBtn"),disconnectBtn:$("#disconnectBtn"),startBtn:$("#startBtn"),stopBtn:$("#stopBtn"),modelStatus:$("#modelStatus"),serialStatus:$("#serialStatus"),serialData:$("#serialData"),badge:$("#emotionBadge"),emoji:$("#emotionEmoji"),name:$("#emotionName"),smileMeter:$("#smileMeter"),blinkMeter:$("#blinkMeter"),jawMeter:$("#jawMeter"),browMeter:$("#browMeter"),smileValue:$("#smileValue"),blinkValue:$("#blinkValue"),jawValue:$("#jawValue"),browValue:$("#browValue"),manualTab:$("#manualTab"),cameraTab:$("#cameraTab"),manualPanel:$("#manualPanel"),cameraPanel:$("#cameraPanel"),manualEmotionName:$("#manualEmotionName"),matrixPreview:$("#matrixPreview")};
let FaceLandmarker,DrawingUtils,landmarker,stream,serialPort,writer,recognizing=false,modelReady=false,cameraReady=false,lastVideoTime=-1,lastSent="",candidate="NEUTRAL",candidateSince=0;
const labels={SMILE:["웃음","😊","smile"],SLEEPY:["졸림","😴","sleepy"],SURPRISE:["놀람","😮","surprise"],NEUTRAL:["중립","●","neutral"]};

function updateRecognitionState(){e.startBtn.disabled=!(modelReady&&cameraReady)}
async function setupAI(){try{const visionModule=await import("https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/+esm");FaceLandmarker=visionModule.FaceLandmarker;DrawingUtils=visionModule.DrawingUtils;const vision=await visionModule.FilesetResolver.forVisionTasks("https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/wasm");landmarker=await FaceLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:"https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task",delegate:"GPU"},runningMode:"VIDEO",numFaces:1,outputFaceBlendshapes:true,minFaceDetectionConfidence:.55,minFacePresenceConfidence:.55,minTrackingConfidence:.55});modelReady=true;e.modelStatus.textContent=cameraReady?"카메라·AI 모델 준비 완료":"AI 모델 준비 완료 · 카메라를 시작하세요";updateRecognitionState()}catch(err){e.modelStatus.textContent="AI 모델 로딩 실패 · 인터넷 연결을 확인하세요";console.error(err)}}
async function startCamera(){if(!navigator.mediaDevices?.getUserMedia){e.modelStatus.textContent="HTTPS의 Chrome 또는 Edge에서 열어주세요";return}try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:1280},height:{ideal:720}},audio:false});e.video.srcObject=stream;await e.video.play();cameraReady=true;e.empty.style.display="none";e.cameraBtn.textContent="카메라 켜짐";e.cameraBtn.disabled=true;e.modelStatus.textContent=modelReady?"카메라·AI 모델 준비 완료":"카메라 켜짐 · AI 모델 준비 중...";updateRecognitionState()}catch(err){e.modelStatus.textContent=err.name==="NotAllowedError"?"카메라 권한이 차단되었습니다":"카메라를 시작하지 못했습니다";console.error(err)}}
async function connectSerial(){if(!("serial" in navigator)){e.serialStatus.textContent="Chrome 또는 Edge에서 HTTPS로 열어주세요";return}try{serialPort=await navigator.serial.requestPort();await serialPort.open({baudRate:9600});writer=serialPort.writable.getWriter();e.serialStatus.textContent="Arduino 연결됨 · 9600 baud";e.connectBtn.disabled=true;e.disconnectBtn.disabled=false}catch(err){if(err.name!=="NotFoundError")e.serialStatus.textContent="연결 실패: "+err.message}}
async function disconnectSerial(){try{if(writer){writer.releaseLock();writer=null}if(serialPort){await serialPort.close();serialPort=null}e.serialStatus.textContent="연결되지 않음 · 9600 baud";e.connectBtn.disabled=false;e.disconnectBtn.disabled=true}catch(err){console.error(err)}}
const score=(map,name)=>map.get(name)||0;
function meter(key,value){e[key+"Meter"].value=value;e[key+"Value"].textContent=Math.round(value*100)+"%"}
function classify(map){const smile=(score(map,"mouthSmileLeft")+score(map,"mouthSmileRight"))/2,blink=(score(map,"eyeBlinkLeft")+score(map,"eyeBlinkRight"))/2,jaw=score(map,"jawOpen"),brow=score(map,"browInnerUp");meter("smile",smile);meter("blink",blink);meter("jaw",jaw);meter("brow",brow);let next="NEUTRAL";if(jaw>.48&&brow>.18)next="SURPRISE";else if(blink>.58)next="SLEEPY";else if(smile>.38)next="SMILE";const now=performance.now();if(next!==candidate){candidate=next;candidateSince=now}return now-candidateSince>450?next:lastSent||"NEUTRAL"}
async function sendEmotion(emotion,force=false){if(emotion===lastSent&&!force)return;lastSent=emotion;const [name,emoji,css]=labels[emotion];e.name.textContent=name;e.emoji.textContent=emoji;e.badge.className="emotion-badge "+css;e.serialData.textContent=emotion+" ↵";if(writer){try{await writer.write(new TextEncoder().encode(emotion+"\n"))}catch(err){e.serialStatus.textContent="전송 오류 · 연결을 확인하세요"}}else{e.serialStatus.textContent="표정 선택됨 · 먼저 USB를 연결하세요"}}
function draw(result){e.canvas.width=e.video.videoWidth;e.canvas.height=e.video.videoHeight;const ctx=e.canvas.getContext("2d");ctx.clearRect(0,0,e.canvas.width,e.canvas.height);if(result.faceLandmarks?.[0]){const drawing=new DrawingUtils(ctx);drawing.drawConnectors(result.faceLandmarks[0],FaceLandmarker.FACE_LANDMARKS_FACE_OVAL,{color:"#58ddff",lineWidth:2});drawing.drawConnectors(result.faceLandmarks[0],FaceLandmarker.FACE_LANDMARKS_LIPS,{color:"#ff6b5d",lineWidth:2})}}
async function loop(){if(!recognizing)return;if(e.video.currentTime!==lastVideoTime&&e.video.readyState>=2){lastVideoTime=e.video.currentTime;const result=landmarker.detectForVideo(e.video,performance.now());draw(result);if(result.faceBlendshapes?.[0]){const map=new Map(result.faceBlendshapes[0].categories.map(c=>[c.categoryName,c.score]));await sendEmotion(classify(map))}}requestAnimationFrame(loop)}
function startRecognition(){if(!modelReady||!cameraReady)return;recognizing=true;e.startBtn.disabled=true;e.stopBtn.disabled=false;loop()}
function stopRecognition(){recognizing=false;updateRecognitionState();e.stopBtn.disabled=true;e.canvas.getContext("2d").clearRect(0,0,e.canvas.width,e.canvas.height)}
function setMode(mode){const manual=mode==="manual";e.manualTab.classList.toggle("active",manual);e.cameraTab.classList.toggle("active",!manual);e.manualTab.setAttribute("aria-selected",manual);e.cameraTab.setAttribute("aria-selected",!manual);e.manualPanel.classList.toggle("active",manual);e.cameraPanel.classList.toggle("active",!manual);e.manualPanel.hidden=!manual;e.cameraPanel.hidden=manual;if(manual&&recognizing)stopRecognition()}
function selectManualEmotion(emotion,button){document.querySelectorAll("[data-emotion]").forEach(b=>b.classList.remove("selected"));button.classList.add("selected");const [name,emoji]=labels[emotion];e.manualEmotionName.textContent=name;e.matrixPreview.querySelector(".pixel-face").textContent=emoji;sendEmotion(emotion,true)}

e.manualTab.addEventListener("click",()=>setMode("manual"));e.cameraTab.addEventListener("click",()=>setMode("camera"));document.querySelectorAll("[data-emotion]").forEach(button=>button.addEventListener("click",()=>selectManualEmotion(button.dataset.emotion,button)));e.cameraBtn.addEventListener("click",startCamera);e.connectBtn.addEventListener("click",connectSerial);e.disconnectBtn.addEventListener("click",disconnectSerial);e.startBtn.addEventListener("click",startRecognition);e.stopBtn.addEventListener("click",stopRecognition);window.addEventListener("beforeunload",()=>stream?.getTracks().forEach(t=>t.stop()));setupAI();
